<?php

// SPDX-FileCopyrightText: 2026 Nextcloud GmbH and Nextcloud contributors
// SPDX-License-Identifier: MIT

declare(strict_types=1);

namespace Nextcloud\ReleaseTools\Tests\Updater;

use Nextcloud\ReleaseTools\Updater\Bump;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\TestCase;

/**
 * What: runs the PHP updater Bump against the same base fixtures + scenarios as
 * the old bash snapshot harness (tests/updater-script) and asserts byte-for-byte
 * identical config/releases.json, config/major_versions.json and feature files.
 *
 * Why: proves the PHP port reproduces update-updater-server.sh exactly across
 * every release shape (patch, RC bump, beta bump, beta->rc, first stable, first
 * beta). config.php is excluded - it is generated by the updater_server Makefile,
 * not by us.
 */
final class BumpParityTest extends TestCase
{
    private const FIXTURES = __DIR__ . '/../fixtures/updater';

    // Deterministic 344-char fake signatures, identical to the bash harness.
    private const FAKE_BZ2 = 'TestBZ2Sig000000000000000000000000000000000000000000000000000000TestBZ2Sig000000000000000000000000000000000000000000000000000000TestBZ2Sig000000000000000000000000000000000000000000000000000000TestBZ2Sig000000000000000000000000000000000000000000000000000000TestBZ2Sig000000000000000000000000000000000000000000000000000000TestBZ2Sig000000000000==';
    private const FAKE_ZIP = 'TestZIPSig000000000000000000000000000000000000000000000000000000TestZIPSig000000000000000000000000000000000000000000000000000000TestZIPSig000000000000000000000000000000000000000000000000000000TestZIPSig000000000000000000000000000000000000000000000000000000TestZIPSig000000000000000000000000000000000000000000000000000000TestZIPSig000000000000==';

    /** @return iterable<string, array{string}> */
    public static function scenarios(): iterable
    {
        foreach (glob(self::FIXTURES . '/scenarios/*', GLOB_ONLYDIR) ?: [] as $dir) {
            yield basename($dir) => [basename($dir)];
        }
    }

    #[DataProvider('scenarios')]
    public function testParity(string $scenario): void
    {
        $scenarioDir = self::FIXTURES . '/scenarios/' . $scenario;
        $args = $this->parseEnv($scenarioDir . '/args.env');

        $work = sys_get_temp_dir() . '/bump-' . $scenario . '-' . bin2hex(random_bytes(4));
        $this->copyTree(self::FIXTURES . '/base', $work);
        if (is_dir($scenarioDir . '/override')) {
            $this->copyTree($scenarioDir . '/override', $work);
        }

        // first-beta opens a new major; the harness recorded minPHP 8.2 for it.
        $minPhp = $scenario === 'first-beta' ? '8.2' : '8.1';
        (new Bump($work))->run(
            $args['TAG'],
            self::FAKE_BZ2,
            self::FAKE_ZIP,
            $args['INTERNAL_VERSION'],
            isset($args['DEPLOY']) ? (int) $args['DEPLOY'] : null,
            $minPhp,
        );

        $expectedDir = $scenarioDir . '/expected';
        foreach ($this->comparableFiles($expectedDir) as $rel) {
            $this->assertSame(
                file_get_contents("{$expectedDir}/{$rel}"),
                file_get_contents("{$work}/{$rel}"),
                "{$scenario}: {$rel} differs from the bash oracle",
            );
        }
        $this->removeTree($work);
    }

    /** @return list<string> expected files we own (everything except config.php) */
    private function comparableFiles(string $expectedDir): array
    {
        $files = [];
        $it = new \RecursiveIteratorIterator(new \RecursiveDirectoryIterator($expectedDir, \FilesystemIterator::SKIP_DOTS));
        foreach ($it as $file) {
            $rel = substr($file->getPathname(), strlen($expectedDir) + 1);
            if ($rel !== 'config/config.php') {
                $files[] = $rel;
            }
        }
        sort($files);
        return $files;
    }

    /** @return array<string, string> */
    private function parseEnv(string $path): array
    {
        $env = [];
        foreach (file($path, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES) as $line) {
            if ($line[0] === '#' || !str_contains($line, '=')) {
                continue;
            }
            [$k, $v] = explode('=', $line, 2);
            $env[trim($k)] = trim($v);
        }
        return $env;
    }

    private function copyTree(string $src, string $dst): void
    {
        $it = new \RecursiveIteratorIterator(
            new \RecursiveDirectoryIterator($src, \FilesystemIterator::SKIP_DOTS),
            \RecursiveIteratorIterator::SELF_FIRST,
        );
        foreach ($it as $item) {
            $target = $dst . '/' . substr($item->getPathname(), strlen($src) + 1);
            if ($item->isDir()) {
                @mkdir($target, 0o777, true);
            } else {
                @mkdir(dirname($target), 0o777, true);
                copy($item->getPathname(), $target);
            }
        }
    }

    private function removeTree(string $dir): void
    {
        $it = new \RecursiveIteratorIterator(
            new \RecursiveDirectoryIterator($dir, \FilesystemIterator::SKIP_DOTS),
            \RecursiveIteratorIterator::CHILD_FIRST,
        );
        foreach ($it as $item) {
            $item->isDir() ? @rmdir($item->getPathname()) : @unlink($item->getPathname());
        }
        @rmdir($dir);
    }
}
