# SPDX-FileCopyrightText: 2026 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: MIT

name: Release pipeline
run-name: "Release ${{ inputs.tag }}"

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g., v34.0.1)'
        required: true

jobs:
  tag:
    if: startsWith(inputs.tag, 'v')
    uses: ./.github/workflows/release-tag.yml
    with:
      tag: ${{ inputs.tag }}
    secrets: inherit

  changelog:
    needs: tag
    if: startsWith(inputs.tag, 'v')
    uses: ./.github/workflows/release-changelog.yml
    with:
      tag: ${{ inputs.tag }}
    secrets: inherit

  build:
    needs: [tag, changelog]
    if: startsWith(inputs.tag, 'v')
    uses: ./.github/workflows/release-build.yml
    with:
      tag: ${{ inputs.tag }}
    secrets: inherit

  updater:
    needs: build
    if: startsWith(inputs.tag, 'v')
    uses: ./.github/workflows/release-updater.yml
    with:
      tag: ${{ inputs.tag }}
    secrets: inherit
